######################################################################
# Automatically generated by qmake (1.07a) Wed Jul 18 14:59:47 2012
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += communicationthread.h mywindow.h openglwidget.h structures.h
SOURCES += communicationthread.cpp main.cpp mywindow.cpp openglwidget.cpp

QT += opengl
